---
title: "DTE Website"
subtitle: "Space Launch Provider Website"
# use quarto markdown to 
---

# Idea
This website was an idea I had since high school, one that became a reality as part of a web development class my first semester of college. The thought was that info on rockets and launch providers was far to spread out and difficult to find, so I took it upon myself to compile a 'wiki' of sorts on six major rocket launch providers. The infor includes major rockets, noteable missions, their history, successes, etc. While it may not be as flush with information as company specific websites, it has a good over-arching collection of information. I made the site completely from scratch, coding the html, css, and javascript myself, as well as all of the research. 

# Website

Below is the website publicly published online through github pages. 

[DTE Space](https://carboaluminate67.github.io/wdd130/space/)

# Repository

This is a backend view of how I created the website, a project that is part of my web development repository. You will also find other small websites and experiments in this repo from other classwork. 

[WDD Repo](https://github.com/CarboAluminate67/wdd130)
