---
title: "Hazardous NEO"
subtitle: "Machine Learning Predicts Hazardous Asteroids"
# use quarto markdown to 
---

# Idea
Out of my own curiosity, and in an effort to learn and practice machine learning, I sought to create a model that could predict if a Near Earth Object was 'potentially hazardous'. I was able to find an online dataset of NEO recorded by NASA, about 10% of which were considered potentially hazardous. This label comes from a multitude of factors, including size, distance from Earth, relative velocity, and more. I endeavored to create my own Machine Learning Classifier to predict if an asteroid would be considered hazardous based on these factors. Ultimately, after testing with both GDBT and Random Forest trees, the latter had better performance with ~93% accuracy. I used techniques such as oversampling the minority class, decreasing the learning rate due to the high number of instances, etc. 

# Repository
Here is the public GitHub repository in which the project was created, using python and sklearn. I even modified user input in order to make predictions on new asteroids that could be discovered. 

[NEO Repo](https://github.com/CarboAluminate67/NearEarthObjects)


